"""empty message

Revision ID: 3f006ae9da70
Revises: 076404fe183b
Create Date: 2022-12-27 11:52:25.185724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f006ae9da70'
down_revision = '076404fe183b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_confirmation_expire', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_confirmation_expire')
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
